# Dependencies
gems: [jekyll-paginate]

markdown:         kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Sprung Canary'
tagline:          'Barely making it out alive'
description:      'Barely making it out alive'
url:              http://sprungcanary.net
baseurl:          '/'

feed:
  copyright:      'Copyright (c) 2015, Bret Young; all rights reserved.'

author:
  name:           'Bret Young'
  url:            http://sprungcanary.net

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/hby

twitter:
  name1:           '@sprungcanary'
  url1:            https://twitter.com/sprungcanary
  name2:           '@hby'
  url2:            https://twitter.com/hby
